site_name: Mathesar Wiki
site_url: https://wiki.mathesar.org/
repo_url: https://github.com/centerofci/mathesar-wiki/
repo_name: centerofci/mathesar-wiki


plugins:
  - search:
      lang: en
  - awesome-pages
  - redirects:
      redirect_maps:
        'community/setup_in_windows.md': 'https://github.com/centerofci/mathesar/blob/develop/DEVELOPER_GUIDE.md'
        'community/contributing.md': 'https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md'
        'engineering/common-issues.md': 'https://github.com/centerofci/mathesar/blob/develop/DEVELOPER_GUIDE.md'
        'engineering/setup.md': 'https://github.com/centerofci/mathesar/blob/develop/DEVELOPER_GUIDE.md'
        'engineering/architecture/api-standards.md': 'https://github.com/centerofci/mathesar/blob/develop/mathesar/api/STANDARDS.md'
        'engineering/architecture/front-end-standards.md': 'https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/STANDARDS.md'
        'engineering/setup/common-issues.md': 'https://github.com/centerofci/mathesar/blob/develop/DEVELOPER_GUIDE.md'
        'engineering/standards/api.md': 'https://github.com/centerofci/mathesar/blob/develop/mathesar/api/STANDARDS.md'
        'engineering/standards/frontend.md': 'https://github.com/centerofci/mathesar/blob/develop/mathesar_ui/STANDARDS.md'

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
      - content.code.copy
      - navigation.indexes
  font:
    text: Nunito Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - smarty
  - tables
  - toc:
      title: On this page
      permalink: true
